{"name": "Проверка, если создать пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "start": 1723981983697, "stop": 1723981984009, "uuid": "5684bc7f-29a9-4d54-bc40-8cbe380f4941", "historyId": "fc376cd2ad665f7615a77d14a1f2a331", "testCaseId": "fc376cd2ad665f7615a77d14a1f2a331", "fullName": "tests.test_courier_creation.TestCourierCreation#test_create_courier_with_repeating_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "DESKTOP-A7QEVR5"}, {"name": "thread", "value": "8708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creation"}]}